site_name: 'EDUC'
repo_url: 'https://github.com/lpsouza/educ/'
lang: pt
google_analytics: ['UA-105361937-2', 'educ.luizsouza.com']
theme:
  name: 'material'
  palette:
    scheme: slate
    primary: deep purple
    accent: deep purple
markdown_extensions:
    - codehilite
nav:
    - '.NET Core':
        - 'Básico': '/dotnet/basics/'
        - 'Orientação a Objetos': '/dotnet/oop/'
