site_name: 'EDUC'
repo_url: 'https://github.com/lpsouza/educ/'
lang: pt
theme:
  name: 'material'
markdown_extensions:
    - codehilite
nav:
    - '.NET Core':
        - 'Básico': '/dotnet/basics/'
        - 'Orientação a Objetos': '/dotnet/object-oriented/'
