site_name: 'EDUC'
repo_url: 'https://github.com/lpsouza/educ/'
lang: pt
theme:
  name: 'material'
markdown_extensions:
- codehilite
nav:
  - 'C#':
    - 'Conhecendo C# com .NET Core': '/csharp-e-dotnet/'
    - 'Hello World': '/csharp-e-dotnet/hello-world/'
    - 'Olá objetos': '/csharp-e-dotnet/objetos/'
