name: Educ-CI
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Docker Run Action
        uses: addnab/docker-run-action@v1
        with:
          image: squidfunk/mkdocs-material:latest
          options: -v ${{github.workspace}}:/docs
          run: |
            ls -l /docs
            mkdocs gh-deploy
