name: Educ-CI
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Run within Docker
        uses: mosteo-actions/docker-run@v1
        with:
          image: squidfunk/mkdocs-material:latest
          params: -v $GITHUB_WORKSPACE:/docs
          command: mkdocs gh-deploy
