name: Educ-CI
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2.3.4
    - name: Run within Docker
      uses: mosteo-actions/docker-run@v1
      with:
        image: squidfunk/mkdocs-material:latest
        params: -v $GITHUB_WORKSPACE:/docs
        command: gh-deploy --force
